### PR TITLE
fix rows_per_page error

### PR DESCRIPTION
**Pull request by cssailing**
fix the error of rows_per_page select all option value -1 
option === -1

### CODE REVIEW

**Comment by MicroDroid** [comment]
I haven't tested the fork yet but what does this exactly fix? I suppose this merely breaks the component instead of fixing anything. :thinking:

**Comment by cssailing** [comment]
when you have select the option all, the option value will be -1, fixed the value option as
:value="option === -1 ? rows.length : option"
make the all select work

**Comment by cssailing** [comment]
you can view the demo-Custom pagination table, select show all, report errors

**Comment by MicroDroid** [comment]
Alright I'll check this out in a moment.

**Comment by MicroDroid** [comment]
Thanks for your effort in making this PR, however, I opted into a slightly different solution to cover some other edge cases that can occur in the 5e2d1aeee5b562a568a941da3ad603289e5d10aa

:tada:

**Pull request closed without merging**
