### PR TITLE
Disable fuzzy search

### PR DESCRIPTION
**Pull request by thepill**
**Current:**
At the moment searching the table returns all `fuzzy` results. 

**Expected:**
Searching should return only `exact` matches.

### CODE REVIEW

**Comment by MicroDroid** [comment]
Why does it have to be exact and not fuzzy? Fuzzy makes it easier to reach your target row while still ordering fuzzy results in such a way that exact results and always first

**Comment by thepill** [comment]
I found it confusing searching for a specific name and got 5 results back although the name was exactly to only one result. IMO i think you could remove fusejs tottaly :)

**Comment by thepill** [comment]
Or we could make this a `prop` like `<datatable ... fuzzy-search>

**Comment by MicroDroid** [comment]
@thepill A prop to disable fuzzy searching would be best and easy to implement. I think fuzzy-searching being on by default would be nice maybe (or not?). Either way I'll merge the pull request if you implement the prop to disable/enable fuzzy searching.

:+1:

**Comment by MicroDroid** [comment]
Thanks a lot

**Pull request merged**
