### PR TITLE
Table responsiveness

### PR DESCRIPTION
**Pull request by TimothyMee**
PR #47 had some issues that needed to be fixed.
This commit fixes those issues.

- Table responsiveness has been made optional
- The scrollback only appears when needed and not permanently visible.

### CODE REVIEW

**Comment by MicroDroid** [comment]
This is still a bad solution. How would the plugin user determine the table needs to be responsive or not?

**Comment by TimothyMee** [comment]
Exactly my thought with the previous solution, the user shouldn't have to worry about the responsiveness, it should be out of the box. But in your comment to the previous solution, you stated that the responsiveness

> "should be entirely optional"

Except I misunderstood.

I thought about it and handing control of the table responsiveness to the plugin user isn't such a bad idea.

As a user, I might decide to just use bootstrap's "table-responsive" on the parent div and not want the table provided responsiveness.

**Comment by MicroDroid** [comment]
Ah no, what I meant by that rather is the scrollbar should show up or not automatically as data requires.

i.e. if the columns are too jambled that it can't fit, a scrollbar should show and the table should stop shrinking. We also need a way to handle rows with exceedingly large data somehow, or we could leave truncating up to the user?

It requires a bit of thought to get this right but I am not exactly free in the meantime to work on fixing this.

I'd appreciate any thoughts you may have.

**Comment by TimothyMee** [comment]
Ohh Ok. I will look into that.

**Pull request closed without merging**
